name: Manual Python Script Run

on:
  workflow_dispatch:

jobs:
  run-python-scripts:
    runs-on: ubuntu-22.04  # Použitie Ubuntu 22.04.4 LTS

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Nastavenie Pythonu 3.12

    - name: Install Poppler
      run: |
        sudo apt-get update
        sudo apt-get install -y poppler-utils

    - name: Install wkhtmltopdf
      run: sudo apt-get install -y ./wkhtmltox_0.12.6.1-2.jammy_amd64.deb

    - name: Install Python dependencies
      run: |
        python3.12 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Plznička
      run: python3.12 -m Python.restauracie.plznicka.plznicka
      continue-on-error: true  # Pokračovať aj v prípade chyby

    - name: Blackdog
      run: python3.12 -m Python.restauracie.blackdog.blackdog
      continue-on-error: true  # Pokračovať aj v prípade chyby

    - name: Radničná
      run: python3.12 -m Python.restauracie.radnicna.radnicna
      continue-on-error: true  # Pokračovať aj v prípade chyby

    - name: Makalu
      run: python3.12 -m Python.restauracie.makalu.makalu
      continue-on-error: true  # Pokračovať aj v prípade chyby

    - name: UpdateWEB
      run: python3.12 -m Python.main.update_web
      continue-on-error: true  # Pokračovať aj v prípade chyby

    - name: Configure Git
      run: |
        git config --global user.name 'Macloggerov BOT'
        git config --global user.email '31780197+Maclogger@users.noreply.github.com'

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Aktualizácia súborov."
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
