name: Manual Python Script Run

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 0-5'    # NED-PIA 4:00
    - cron: '0 6 * * 0-5'    # NED-PIA 6:00
    - cron: '0 9 * * 0-5'    # NED-PIA 9:00
    - cron: '0 10 * * 0-5'   # NED-PIA 10:00
    - cron: '0 11 * * 0-5'   # NED-PIA 11:00
    - cron: '0 18 * * 0-5'   # NED-PIA 18:00
    - cron: '0 22 * * 0-5'   # NED-PIA 22:00
    - cron: '0 12 * * 6'     # SOB 12:00
jobs:
  run-python-scripts:
    runs-on: ubuntu-22.04  # Použitie Ubuntu 22.04.4 LTS
    env:
      TZ: 'Europe/Bratislava'  # Nastavenie časovej zóny

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Nastavenie Pythonu 3.12

    - name: Install Poppler
      run: |
        sudo apt-get update
        sudo apt-get install -y poppler-utils

    - name: Install wkhtmltopdf
      run: sudo apt-get install -y ./wkhtmltox_0.12.6.1-2.jammy_amd64.deb

    - name: Install Python dependencies
      run: |
        python3.12 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Plznička
      run: python3.12 -m Python.restauracie.plznicka.plznicka
      continue-on-error: true  # Pokračovať aj v prípade chyby

    - name: Blackdog
      run: python3.12 -m Python.restauracie.blackdog.blackdog
      continue-on-error: true  # Pokračovať aj v prípade chyby

    - name: Radničná
      run: python3.12 -m Python.restauracie.radnicna.radnicna
      continue-on-error: true  # Pokračovať aj v prípade chyby

    - name: Makalu
      run: python3.12 -m Python.restauracie.makalu.makalu
      continue-on-error: true  # Pokračovať aj v prípade chyby

    - name: Kozlovňa
      run: python3.12 -m Python.restauracie.kozlovna.kozlovna
      continue-on-error: true  # Pokračovať aj v prípade chyby

    - name: UpdateWEB
      run: python3.12 -m Python.main.update_web
      continue-on-error: true  # Pokračovať aj v prípade chyby

    - name: Commit and push changes
      run: |
        git config --global user.name 'Macloggerov BOT'
        git config --global user.email 'macloggers_bot@users.noreply.github.com'
        git add .
        git commit -m "Aktualizácia súborov."
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
